/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import EDD.NodeAVL;
import EDD.NodeLD;
import Hilos.AutoAVL;
import Hilos.ManualAVL;
import Hilos.Mostrar;
import Object.User;
import java.awt.Image;
import java.io.File;
import java.net.URL;
import java.security.Principal;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import proyecto_2.Proyecto_2;

/**
 *
 * @author Oscar C
 */
public class AVLTree extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form AVLTree
     */
    User u;
    NodeLD as;
    Thread actualizar;
    Thread mostrar;
    NodeLD first;

    public AVLTree(User X) {
        initComponents();
        this.u = X;
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBack = new javax.swing.JButton();
        jSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jButtonInsert = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jTextFieldDelete = new javax.swing.JTextField();
        Cargar = new javax.swing.JButton();
        jCBTipo = new javax.swing.JComboBox();
        jLabel = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jLabelDesc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBack.setText("Regresar");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 95, -1));

        jSlider.setMajorTickSpacing(1);
        jSlider.setMaximum(10);
        jSlider.setMinimum(1);
        jSlider.setPaintTicks(true);
        jSlider.setValue(5);
        jSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderStateChanged(evt);
            }
        });
        getContentPane().add(jSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, 134, -1));

        jLabel1.setText("Velocidad: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jButtonInsert.setText("Insertar");
        jButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 88, -1));

        jButtonDelete.setText("Eliminar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 88, -1));

        jTextFieldDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 103, -1));

        Cargar.setText("Carga");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        getContentPane().add(Cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 88, -1));

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Automatico", "Manual" }));
        jCBTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jCBTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        getContentPane().add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, 190, 30));
        getContentPane().add(jLabelImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 630, 630));
        getContentPane().add(jLabelDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 210, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        Usuario ventanA = new Usuario(this.u);
        this.setVisible(false);
        ventanA.setVisible(true);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderStateChanged
        System.out.println(jSlider.getValue());
    }//GEN-LAST:event_jSliderStateChanged

    private void jTextFieldDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDeleteActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
        if (archivo != null) {
            Proyecto_2.avl.clear();

            Proyecto_2.listTree(archivo.getAbsolutePath());
            if (jCBTipo.getSelectedItem() == "Manual") {
                JOptionPane.showMessageDialog(null, "Datos cargados para insercion manual");
                as = Proyecto_2.doble.getFirst();
                first = Proyecto_2.doble.getFirst();
            } else if (jCBTipo.getSelectedItem() == "Automatico") {
                System.out.println("Automatico");
                NodeLD s = Proyecto_2.doble.getFirst();
                first = Proyecto_2.doble.getFirst();

                AutoAVL ac = new AutoAVL(jLabel, s, jSlider.getValue(), jLabelDesc, jLabelImage);
                ac.start();

            }
        }
    }//GEN-LAST:event_CargarActionPerformed

    private void jButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertActionPerformed
        //Inserta de uno en uno
        if (as != null) {
            ManualAVL mavl = new ManualAVL(jLabel, as, jSlider.getValue(), jLabelDesc, jLabelImage);
            mavl.start();
            as = as.getNext();
        } else {
            JOptionPane.showMessageDialog(null, "Arbol terminado");
        }
    }//GEN-LAST:event_jButtonInsertActionPerformed

    private void jCBTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AVLTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AVLTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AVLTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AVLTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                // new AVLTree(this.u).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cargar;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JComboBox jCBTipo;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDesc;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JSlider jSlider;
    private javax.swing.JTextField jTextFieldDelete;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        if (ct == actualizar) {

        } else if (ct == mostrar) {

        }

    }

}
